const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

function convertToBool(text, fault = 'true') {
    return text === fault ? true : false;
}

module.exports = {
    SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU0ZhcG1vZEkvaThudE1DNEtpcDdzbnpid3VBNVFKL0krckYvVU9DVUlGWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUHBCTHBRSVdPNjU3MHpMSkJrZWVycVZaV0UrMTNHTXFkTmlBODZGK0lXQT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJhTTN0TDU3bHBXK0xrWitTQzhDTGYraEpoNmtqOCtRbFZ1RzJCY0hyNVhNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ0QXE4VnFxTEN5K1NjbTFiZTNqZlByM0M1Ym81YlRidjRkaEx0VDJxYW13PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImVQTEdqT1VSOERrTGZGdk96S0FmOEtOVXdhSUgyTndLRmpzeDZqeVVHRjA9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImJpRExIa3p3enRyczR4UmtOaVYzcitXc2NQZ0RHL3U0aEttRlhNZ0wxMHc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0NMUWlTK1FFQys1ZmxRY29LMGpHYnlDVGswUy9hVVE5d0Myd3c0L3Btbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVmZEK1VoZEx6cnVRZ1JBU2doeldkeHZVZ3ltQ3VqQ2JaYzZ0TWRoT2ducz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkFXL0c1MDk3aDdKNW5oWkxsNlVnMHMxdWRIS1VnSlZJVHBiNEN5eU03MEtmdmUways3QWFRTThQZWNLV1czZXU1UnM2TjN2R2RBWGpISmU5dE5FTURBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODQsImFkdlNlY3JldEtleSI6IlNvY0RjWlFUM1dJOEZqU1ZDOENnaGVkZmc3RVpFWlE2TkMvRnJuK0J6b1E9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IkdYcGJoV21PU3FpcUoyMThETFF2RFEiLCJwaG9uZUlkIjoiYzY1ZWFlMzctZDUwOC00OGE4LWExMmEtYjdmZTA2Yjg3MGZlIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImhXVkdQNjlmS1h1Q3FlNGtSM0E4RDl3emRwVT0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJHN1dpS1NiTi81Q0tnQVVxS3lENE83SzRzcm89In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiRFpEMktSN0oiLCJtZSI6eyJpZCI6IjI1NTczODEzMjQ0Nzo1M0BzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTWVGMXdFUTErNlh2QVlZQmlBQUtBQT0iLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiSVEzVGhPVm1Xb3k5MWlWSEZvZ0VKLzlaMmlNbythWDdJTjdUMHlRdHRVND0iLCJhY2NvdW50U2lnbmF0dXJlIjoiRFBaNDUwaU5jTVhSazBNNUJDMktYRTlZU3lYQW83NUU5M3loMVhYSS9lQ1JJZitxbDhPUFdKR0Jaam8zL2QzV2lhSnM1THczS0RuSVdySHpHcUVJQ2c9PSIsImRldmljZVNpZ25hdHVyZSI6ImNKRU9Qa0tmUXRURDl4MG91MVNpdE5LYXVZUFp4R1FiN3I1ZXduMitNeGRoTnAxZWc0NlRTd2haeTU1NWVjOUFpL0FTRDlwR1F0cThFUjNPckVXb0RRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU1NzM4MTMyNDQ3OjUzQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlNFTjA0VGxabHFNdmRZbFJ4YUlCQ2YvV2RvaktQbWwreURlMDlNa0xiVk8ifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzY4MzI4NjgsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBQU43In0=",
    CAPTION: process.env.CAPTION || "HUMBLE-BOY",
    AUTO_READ_STATUS: process.env.AUTO_READ_STATUS || "true",
    AUTO_REPLY_STATUS: process.env.AUTO_REPLY_STATUS || "true",
    READ_MESSAGE: process.env.READ_MESSAGE || "false", // Added auto-read configuration
    MODE: process.env.MODE || "private",
    AUTO_VOICE: process.env.AUTO_VOICE || "true",
    AUTO_STICKER: process.env.AUTO_STICKER || "false",
    AUTO_REPLY: process.env.AUTO_REPLY || "false",
    ALIVE_IMG: process.env.ALIVE_IMG || "https://files.catbox.moe/3kdkf6.jpg",
    ALIVE_MSG: process.env.ALIVE_MSG || "HII DEAR IM ONLINE I'M HUMBLE-BOY WHATSAPP BOT 👍🤠",
    ANTI_LINK: process.env.ANTI_LINK || "true",
    ANTI_BAD: process.env.ANTI_BAD || "true",
    PREFIX: process.env.PREFIX || ".",
    FAKE_RECORDING: process.env.FAKE_RECORDING || "true",
    FAKE_TYPING: process.env.FAKE_TYPING || "false",
    ALWAYS_ONLINE: process.env.ALWAYS_ONLINE || "true",
    CURRENT_STATUS: process.env.CURRENT_STATUS || "true",
    AUTO_REACT: process.env.AUTO_REACT || "true",
    HEART_REACT: process.env.HEART_REACT || "true",
    OWNER_REACT: process.env.OWNER_REACT || "true",
    BOT_NAME: process.env.BOT_NAME || "HUMBLE-BOY",
    STATUS_REPLY: process.env.STATUS_REPLY || "`✅ your status seen 👀`",
    OMDB_API_KEY: process.env.OMDB_API_KEY || "76cb7f39", // omdbapi.com
};
